//
//  ExternalNavigationRepresentation.swift
//  AppCoreModule
//
//  Created by Car mudi on 12/03/24.
//

/// `NOTE:` - This file is generated by script don't forget to import your CoreModule here
///  Because the file is sperated in CoreModule. if you want to use your own code you can delete this file
/// `Example:``
/// `public protocol PresentableScreen: RepresentableViewController {}`

public protocol SecondPresentableScreen: RepresentableViewController {}
public protocol ThirdPresentableScreen: RepresentableViewController {}
