//
//  __MODULE_PREFIX__.swift
//  __MODULE_PREFIX__
//
//  Created by Car mudi on 11/07/23.
//

import Swinject
/// `NOTE:` - This file is generated by script don't forget to import your CoreModule here
///  Because the file is sperated in CoreModule. if you want to use your own code you can delete this file

public final class __MODULE_PREFIX__Configuration {

    public private(set) static var resourceBundle: Bundle = {
        return Bundle(for: __MODULE_PREFIX__.self).resource
    }()

    public static let shared = __MODULE_PREFIX__()

    public init() {
    }

    @discardableResult
    public static func configureAssembler(in assembler: Assembler) -> ModuleAssembler {
        let assembler: ModuleAssembler = __MODULE_PREFIX__Assembler(in: assembler)

        return assembler
    }
}