//
//  __MODULE_PREFIX__Assembler.swift
//  __MODULE_PREFIX__
//
//  Created by Car mudi on 10/07/23.
//

/// `NOTE:` - This file is generated by script don't forget to import your CoreModule here
///  Because the file is sperated in CoreModule. if you want to use your own code you can delete this file
import Swinject

final class __MODULE_PREFIX__Assembler: ModuleAssembler {

    private(set) var assembler: Assembler

    init(in assembler: Assembler) {
        self.assembler = assembler
        registerManagers()
    }

    public func registerManagers() {
        let assembly: [Assembly] = [
            NavigationManager(),
            ViewControllerManager(),
            ViewModelManager(),
            UseCaseManager(),
            RepositoryManager(),
            DataSourceManager()
        ]

        assembler.apply(assemblies: assembly)
    }
}