//
//  SecondNavigationRoute.swift
//  SecondModule
//
//  Created by Car mudi on 07/03/24.
//

import Swinject
import AppCoreModule
/// `NOTE:` - This file is generated by script don't forget to import your CoreModule here
///  Because the file is sperated in CoreModule. if you want to use your own code you can delete this file

public protocol SecondNavigationService {

    var resolver: Resolver { get }

    var app: AppNavigationService { get }

    func back()

    func openSecondScreen()
}

public class SecondNavigation: SecondNavigationService {

    public var resolver: Resolver

    public var app: AppNavigationService

    public init(resolver: Resolver) {
        self.resolver = resolver
        self.app = resolver.receive(AppNavigationService.self)
    }

    public func back() {
        app.back(animated: true)
    }

    public func openSecondScreen() {
        let secondScreen = resolver.receive() as SecondPresentableScreen
        app.pushViewController(secondScreen.viewController(), animated: true)
    }
}
